version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BROWSERLESS_API_KEY=${BROWSERLESS_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=seo_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
    command: uvicorn src.service:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=seo_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: 