data_collection_task:
  description: >
    WEBSITE BEING ANALYZED: {website_url}

    Analyze and collect SPECIFIC metrics using the tools:
    1. Using BrowserlessScraper, collect and analyze:
       - Meta tags and SEO elements
       - Content structure (headings h1-h6)
       - Keyword frequency and density analysis
       - Internal and external link mapping
       - Images and media inventory
       - Complete URL directory
       - Meta descriptions extraction

    2. Using SubpageAnalyzer, analyze:
       - Page crawl and indexing status
       - Content quality assessment
       - User engagement metrics
       - Internal linking patterns
       - Page authority scoring
       - JavaScript-rendered content

    3. Using LoadingTimeTracker:
       - Page load timing analysis
       - Resource loading sequences
       - Performance bottlenecks
       - Network request patterns
       - Page size measurements
       - Performance ratings

    4. Using MobileTesting:
       - Viewport configuration
       - Mobile responsiveness
       - Touch element spacing
       - Font size accessibility
       - Content scaling
       - Mobile-friendly images
       - Media query implementation
       - Mobile performance metrics
       - User experience factors

    IMPORTANT: Provide NUMERICAL data wherever possible. Do not make assumptions.


  expected_output: >
    ANALYSIS REPORT FOR: {website_url}

    1. Meta Tags Analysis:
       - Total number of meta tags: [X]
       - Most used meta tags:
         * [tag_type]: [count] occurrences
         * [tag_type]: [count] occurrences
    
    2. Content Analysis:
       - Most frequent words:
         * [word]: [count] occurrences
         * [word]: [count] occurrences
       - Word density percentages
    
    3. Content Structure:
       - H1 tags: [X]
       - H2 tags: [X]
       - H3 tags: [X]
       - H4-H6 tags: [X]
       - Total word count: [X]
    
    4. Link Analysis:
       - Internal links: [X]
       - External links: [X]
       - Unique domains linked: [List]
       - Broken links found: [X]
    
    5. Media Inventory:
       - Total images: [X]
       - Images with alt text: [X]
       - Images without alt text: [X]
    
    6. Performance Metrics:
       - Average load time: [X] ms
       - Fastest load: [X] ms
       - Slowest load: [X] ms
       - Sample size: [X]

    7. Mobile Optimization:
       - Viewport Meta Tag: [Yes/No]
       - Text Readability Score: [X]%
       - Tap Target Spacing Score: [X]%
       - Responsive Images Score: [X]%
       - Overall Mobile Score: [X]%

    9. Top Subpages:
       - Number of analyzed pages: [X]
       - Average importance score: [X]
       - Top 5 pages by importance:
         * [URL]: Score [X]
         * Content metrics
         * Link metrics

    Raw Data Summary:
    [Include specific data points found during analysis]
  agent: scraper_agent

analysis_task:
  description: >
    ANALYZING WEBSITE: {website_url}

    Based on the collected numerical data, analyze:
    1. Technical Performance:
       - Compare load times against industry standard (2.5s)
       - Calculate mobile performance score
       - Measure TTFB (Time to First Byte)
    
    2. Content Quality:
       - Calculate keyword density percentages
       - Measure heading structure completeness
       - Analyze meta tag optimization percentage
    
    3. Link Profile:
       - Calculate internal/external link ratio
       - Measure link distribution
       - Identify authority of linked domains

    4. Page Importance:
       - Evaluate content depth
       - Analyze user engagement signals
       - Calculate page authority scores

  expected_output: >
    SEO ANALYSIS REPORT FOR: {website_url}

    1. Performance Scores:
       - Load time percentile: [X]%
       - Mobile optimization: [X]%
       - Technical health: [X]%
    
    2. Content Metrics:
       - Keyword density: [X]%
       - Structure score: [X]%
       - Meta optimization: [X]%
    
    3. Link Analysis:
       - Internal/External ratio: [X]
       - Distribution score: [X]%
       - Domain authority range: [X-Y]

    Page Authority Analysis:
    - Content depth score: [X]%
    - Engagement potential: [X]%
    - Overall authority: [X]%

  agent: analyse_agent

optimization_task:
  description: >
    OPTIMIZATION PLAN FOR: {website_url}

    Based on the statistical analysis, create an optimization plan with:
    1. Priority Issues (List top 5 with metrics)
    2. Expected Impact (Percentage improvements)
    3. Implementation Timeline (With specific milestones)
    4. Page-Specific Recommendations:
       - Content enhancement suggestions
       - Structure improvements
       - Link optimization strategies

  expected_output: >
    OPTIMIZATION RECOMMENDATIONS FOR: {website_url}

    1. Priority Fixes:
       - Issue 1: [Metric] -> [Target]
       - Issue 2: [Metric] -> [Target]
       etc.
    
    2. Impact Forecast:
       - Load time reduction: [X]%
       - SEO score increase: [X]%
       - User engagement: [X]%
    
    3. Key Statistics:
       - Average Load Time: [X]s
       - Most Used Meta Tags: [List]
       - Mobile Compatibility: [X]%
       - Most Frequent Words: [List top 10 with count]
       - TopSubpages [List of subpages with metrics]

    Page-Specific Optimizations:
    1. High-Priority Pages:
       - [Subpage URL]: [Specific recommendations]
    2. Content Gaps:
       - [Identified gaps]
       - [Improvement suggestions]
    3. Structure Enhancements:
       - [Navigation improvements]
       - [Internal linking strategies]

  agent: optimization_agent
