data_collection_task:
  description: >
    WEBSITE BEING ANALYZED: {website_url}

    Analyze and collect SPECIFIC metrics using the tools:

    1. Using SeleniumScraper, collect and count:
       - Meta tags and their types with descriptions
       - Heading structure and content hierarchy
       - Keyword usage and semantic relationships
       - Internal/external link patterns
       - Image optimization status
       - Page structure and content organization

    2. Using LoadingTimeTracker, measure:
       - Page load time distribution
       - Performance bottlenecks
       - Resource loading patterns

    3. Using MobileOptimizationTool, analyze:
       - Responsive design implementation
       - Mobile-specific features
       - Touch target compliance
       - Content adaptation

    4. Using OffPageSEOAnalyzer, examine:
       - Link profile quality and diversity
       - Social media engagement patterns
       - Brand visibility metrics
       - Content distribution effectiveness

    5. Using ReferringDomainAnalyzer, analyze:
       - Referring domain quality
       - Reference context and relevance
       - Authority patterns
       - Industry relationships

    6. Using SubpageAnalyzer, evaluate:
       - Content hierarchy
       - Internal linking structure
       - Page importance distribution
       - Content quality metrics

    IMPORTANT: Provide NUMERICAL data and specific URLs wherever possible.

  expected_output: >
    [Detailed output format with specific metrics and URLs]
  agent: scraper_agent

analysis_task:
  description: >
    ANALYZING WEBSITE: {website_url}

    Based on the collected numerical data, analyze:
    1. Technical Performance:
       - Compare load times against industry standard (2.5s)
       - Calculate mobile performance score
       - Measure TTFB (Time to First Byte)
    
    2. Content Quality:
       - Calculate keyword density percentages
       - Measure heading structure completeness
       - Analyze meta tag optimization percentage
    
    3. Link Profile:
       - Calculate internal/external link ratio
       - Measure link distribution
       - Identify authority of linked domains

    4. Page Importance:
       - Evaluate content depth
       - Analyze user engagement signals
       - Calculate page authority scores

  expected_output: >
    SEO ANALYSIS REPORT FOR: {website_url}

    1. Performance Scores:
       - Load time percentile: [X]%
       - Mobile optimization: [X]%
       - Technical health: [X]%
    
    2. Content Metrics:
       - Keyword density: [X]%
       - Structure score: [X]%
       - Meta optimization: [X]%
    
    3. Link Analysis:
       - Internal/External ratio: [X]
       - Distribution score: [X]%
       - Domain authority range: [X-Y]

    Page Authority Analysis:
    - Content depth score: [X]%
    - Engagement potential: [X]%
    - Overall authority: [X]%

  agent: analyse_agent

optimization_task:
  description: >
    OPTIMIZATION PLAN FOR: {website_url}

    Based on the statistical analysis, create an optimization plan with:
    1. Priority Issues (List top 5 with metrics)
    2. Expected Impact (Percentage improvements)
    3. Implementation Timeline (With specific milestones)

    4. Page-Specific Recommendations:
       - Content enhancement suggestions
       - Structure improvements
       - Link optimization strategies

  expected_output: >
    OPTIMIZATION RECOMMENDATIONS FOR: {website_url}

    1. Priority Fixes:
       - Issue 1: [Metric] -> [Target]
       - Issue 2: [Metric] -> [Target]
       etc.
    
    2. Impact Forecast:
       - Load time reduction: [X]%
       - SEO score increase: [X]%
       - User engagement: [X]%
    
    3. Key Statistics:
       - Average Load Time: [X]s
       - Most Used Meta Tags: [List]
       - Mobile Compatibility: [X]%
       - Most Frequent Words: [List top 10 with count]

    Page-Specific Optimizations:
    1. High-Priority Pages:
       - [URL]: [Specific recommendations]
    2. Content Gaps:
       - [Identified gaps]
       - [Improvement suggestions]
    3. Structure Enhancements:
       - [Navigation improvements]
       - [Internal linking strategies]

  agent: optimization_agent
