data_collection_task:
  description: >
    WEBSITE BEING ANALYZED: {website_url}

    Analyze and collect SPECIFIC metrics using the tools:

    1. Using SeleniumScraper, collect and count:
       - Meta tags and their types
       - Total number of headings (h1-h6) with their distribution
       - Exact keyword count and density percentages
       - Total number of internal and external links
       - Number of images and their alt text status
       - List all unique URLs found
       - Extract and list all meta descriptions

    2. Using LoadingTimeTracker, measure:
       - Exact page load times with millisecond precision
       - Number of samples taken
       - Performance variance

    3. Using MobileOptimizationTool, analyze:
       - Viewport meta tag presence
       - Text readability (font sizes)
       - Tap target spacing
       - Responsive images
       - Mobile compatibility score

    4. Using OffPageSEOAnalyzer, analyze:
       - External linking patterns
       - Social media footprint
       - Brand presence indicators
       - Content distribution

    5. Using SubpageAnalyzer, analyze:
       - Top performing pages
       - Content quality metrics
       - Internal link structure
       - Page importance scores

    IMPORTANT: Provide NUMERICAL data wherever possible. Do not make assumptions.

  expected_output: >
    ANALYSIS REPORT FOR: {website_url}

    1. Meta Tags Analysis:
       - Total number of meta tags: [X]
       - Most used meta tags:
         * [tag_type]: [count] occurrences
         * [tag_type]: [count] occurrences
    
    2. Content Analysis:
       - Most frequent words:
         * [word]: [count] occurrences
         * [word]: [count] occurrences
       - Word density percentages
    
    3. Content Structure:
       - H1 tags: [X]
       - H2 tags: [X]
       - H3 tags: [X]
       - H4-H6 tags: [X]
       - Total word count: [X]
    
    4. Link Analysis:
       - Internal links: [X]
       - External links: [X]
       - Unique domains linked: [List]
       - Broken links found: [X]
    
    5. Media Inventory:
       - Total images: [X]
       - Images with alt text: [X]
       - Images without alt text: [X]
    
    6. Performance Metrics:
       - Average load time: [X] ms
       - Fastest load: [X] ms
       - Slowest load: [X] ms
       - Sample size: [X]

    7. Mobile Optimization:
       - Viewport Meta Tag: [Yes/No]
       - Text Readability Score: [X]%
       - Tap Target Spacing Score: [X]%
       - Responsive Images Score: [X]%
       - Overall Mobile Score: [X]%

    8. Off-Page Analysis:
       - External Link Distribution:
         * Educational links: [X]
         * Government links: [X]
         * Organization links: [X]
         * Commercial links: [X]
       - Authority Score: [X]%
       - Brand Presence Score: [X]%

    9. Referring Domains:
       - Total referring domains: [X]
       - Domain categories distribution:
         * [category]: [count]
       - Strongest references: [List top 5]

    10. Top Subpages:
       - Number of analyzed pages: [X]
       - Average importance score: [X]
       - Top 5 pages by importance:
         * [URL]: Score [X]
         * Content metrics
         * Link metrics

    Raw Data Summary:
    [Include specific data points found during analysis]
  agent: scraper_agent

analysis_task:
  description: >
    ANALYZING WEBSITE: {website_url}

    Based on the collected numerical data, analyze:
    1. Technical Performance:
       - Compare load times against industry standard (2.5s)
       - Calculate mobile performance score
       - Measure TTFB (Time to First Byte)
    
    2. Content Quality:
       - Calculate keyword density percentages
       - Measure heading structure completeness
       - Analyze meta tag optimization percentage
    
    3. Link Profile:
       - Calculate internal/external link ratio
       - Measure link distribution
       - Identify authority of linked domains

    4. Page Importance:
       - Evaluate content depth
       - Analyze user engagement signals
       - Calculate page authority scores

  expected_output: >
    SEO ANALYSIS REPORT FOR: {website_url}

    1. Performance Scores:
       - Load time percentile: [X]%
       - Mobile optimization: [X]%
       - Technical health: [X]%
    
    2. Content Metrics:
       - Keyword density: [X]%
       - Structure score: [X]%
       - Meta optimization: [X]%
    
    3. Link Analysis:
       - Internal/External ratio: [X]
       - Distribution score: [X]%
       - Domain authority range: [X-Y]

    Page Authority Analysis:
    - Content depth score: [X]%
    - Engagement potential: [X]%
    - Overall authority: [X]%

  agent: analyse_agent

optimization_task:
  description: >
    OPTIMIZATION PLAN FOR: {website_url}

    Based on the statistical analysis, create an optimization plan with:
    1. Priority Issues (List top 5 with metrics)
    2. Expected Impact (Percentage improvements)
    3. Implementation Timeline (With specific milestones)

    4. Page-Specific Recommendations:
       - Content enhancement suggestions
       - Structure improvements
       - Link optimization strategies

  expected_output: >
    OPTIMIZATION RECOMMENDATIONS FOR: {website_url}

    1. Priority Fixes:
       - Issue 1: [Metric] -> [Target]
       - Issue 2: [Metric] -> [Target]
       etc.
    
    2. Impact Forecast:
       - Load time reduction: [X]%
       - SEO score increase: [X]%
       - User engagement: [X]%
    
    3. Key Statistics:
       - Average Load Time: [X]s
       - Most Used Meta Tags: [List]
       - Mobile Compatibility: [X]%
       - Most Frequent Words: [List top 10 with count]

    Page-Specific Optimizations:
    1. High-Priority Pages:
       - [URL]: [Specific recommendations]
    2. Content Gaps:
       - [Identified gaps]
       - [Improvement suggestions]
    3. Structure Enhancements:
       - [Navigation improvements]
       - [Internal linking strategies]

  agent: optimization_agent

technical_analysis:
  description: >
    Analyze the technical SEO aspects of {website_url} using the BrowserlessScraper tool.
    
    1. Collect and analyze:
       - All meta tags and their content
       - Heading structure (h1-h6)
       - Internal and external links
       - Image optimization (alt tags, dimensions)
       - Content structure and readability
    
    2. Measure performance:
       - Page load times
       - Mobile optimization scores
       - Technical SEO metrics
    
    3. Provide detailed metrics on:
       - Meta tag coverage
       - Content structure quality
       - Link profile health
       - Image optimization status
       - Overall technical score

content_analysis:
  description: >
    Analyze the content quality and SEO optimization of {website_url}.
    
    1. Using BrowserlessScraper, analyze:
       - Keyword usage and density
       - Content readability scores
       - Content structure and formatting
       - Media usage and optimization
    
    2. Using OffPageSEOAnalyzer, examine:
       - External linking patterns
       - Social media presence
       - Brand visibility metrics
    
    3. Using ReferringDomainAnalyzer, check:
       - Quality of referring domains
       - Context of references
       - Authority of sources

optimization:
  description: >
    Based on the technical and content analysis of {website_url}, provide optimization recommendations.
    
    1. Using SubpageAnalyzer, identify:
       - Top performing pages
       - Pages needing improvement
       - Content gaps
       - Internal linking opportunities
    
    2. Create an action plan for:
       - Technical improvements
       - Content enhancements
       - Link profile optimization
       - User experience improvements
    
    3. Prioritize recommendations by:
       - Impact potential
       - Implementation effort
       - Expected ROI
